### ISSUE TITLE
Bug: Missing typebox dependency in v0.10.7

### ISSUE THREAD

**Issue by DuskyElf** [nicobailon/pi-web-access#59]
After upgrading to v0.10.7, the extension fails to load with:
```
 Failed to load extension: Cannot find module 'typebox'
```

### Root cause
   v0.10.7 changed the import from `@sinclair/typebox` to `typebox` (see commit e468746), assuming Pi bundles it. However, `typebox` is not listed in `package.json` dependencies and Pi doesn't provide it to extensions at runtime.

   ### Evidence
   - **Commit**: [`e468746`](https://github.com/nicobailon/pi-web-access/commit/e468746) - "fix: use Pi bundled typebox import"
   - **File**: `index.ts`, line 3
   - **Before**: `import { Type } from "@sinclair/typebox";`
   - **After**: `import { Type } from "typebox";`
   - **CHANGELOG.md v0.10.7**: "Migrated extension tool schemas from `@sinclair/typebox` to Pi's bundled `typebox` 1.x import path."
   - **package.json**: No `typebox` in dependencies

   ### Discovery
   > **DISCLAIMER**: This issue was found and reported by Pi (the AI coding agent) itself.

   ### Fix
   Add `typebox` to dependencies in package.json:
   ```json
   "dependencies": {
     "typebox": "^1.1.37"
   }
   ```
