### PR TITLE
fix: add typebox dependency for extension loading

### LINKED ISSUE #59: Bug: Missing typebox dependency in v0.10.7
After upgrading to v0.10.7, the extension fails to load with:
```
 Failed to load extension: Cannot find module 'typebox'
```

### Root cause
   v0.10.7 changed the import from `@sinclair/typebox` to `typebox` (see commit e468746), assuming Pi bundles it. However, `typebox` is not listed in `package.json` dependencies and Pi doesn't provide it to extensions at runtime.

   ### Evidence
   - **Commit**: [`e468746`](https://github.com/nicobailon/pi-web-access/commit/e468746) - "fix: use Pi bundled typebox import"
   - **File**: `index.ts`, line 3
   - **Before**: `import { Type } from "@sinclair/typebox";`
   - **After**: `import { Type } from "typebox";`
   - **CHANGELOG.md v0.10.7**: "Migrated extension tool schemas from `@sinclair/typebox` to Pi's bundled `typebox` 1.x import path."
   - **package.json**: No `typebox` in dependencies

   ### Discovery
   > **DISCLAIMER**: This issue was found and reported by Pi (the AI coding agent) itself.

   ### Fix
   Add `typebox` to dependencies in package.json:
   ```json
   "dependencies": {
     "typebox": "^1.1.37"
   }
   ```

### PR DESCRIPTION
**Pull request by DuskyElf**
Fixes: #59 

Add typebox as a dependency to fix extension loading failures in standalone environments.

### Problem
v0.10.7 changed the import from @sinclair/typebox to typebox (commit e468746), expecting Pi to bundle it. However, typebox was not declared in dependencies,

causing runtime failures:
```
Cannot find module 'typebox'
```

### CODE REVIEW

**Comment by nicobailon** [comment]
Thanks for catching this. Current `main` has moved on, already declares `typebox` as a peer dependency, and intentionally ignores/removes `package-lock.json`. Since this branch now conflicts and would reintroduce old package state, I’m closing it as superseded. If we decide `typebox` should be a direct dependency instead, that should be a fresh PR against current `main`.
